#!/bin/sh

CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o teslamate-addr-fix .

if [ $? != 0 ] 
then
	echo "[teslamate-addr-fix] go build failed"
	exit 1
fi

docker build -t waynejz/teslamate-addr-fix:latest .

if [ $? != 0 ] 
then
	echo "[teslamate-addr-fix] docker build failed"
	exit 1
fi